import os

env=Environment(ENV=os.environ, CFLAGS='-g', CXXFLAGS='-g -DDEBUG')
env.ParseConfig('pkg-config gtk+-3.0 laipinyin-2.0 sqlite3 --cflags --libs')

env.Program('laipinyin', source=['imi_gtkwin.cpp', 'laipinyin.cpp'])

# -*- indent-tabs-mode: nil -*- vim:et:ts=4
